name: Build and Save Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build Docker image
      run: docker build -t quay.io/ceph/ceph:v19 .

    - name: Save Docker image
      run: docker save quay.io/ceph/ceph:v19 -o ceph_v19.tar
    - name: Upload Docker image
      uses: actions/upload-artifact@v2
      with:
        name: ceph_v19
        path: ceph_v19.tar
